version: "2"
checks:
  argument-count:
    config:
      threshold: 5
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 500
  method-complexity:
    enabled: false
  method-count:
    config:
      threshold: 25
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
plugins:
  bandit:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        python:
          mass_threshold: 40
  fixme:
    enabled: true
  git-legal:
    enabled: true
  pylint:
    enabled: true
    channel: "beta"
  radon:
    enabled: true
    config:
      threshold: "C"
  sonar-python:
    enabled: true
    config:
      tests_patterns:
        - tests/**
exclude_patterns:
- tests/
